# voldemort configuration file
layout_dirs : 
              - layout
              - include
posts_dir   : posts
post_url    : "%Y/%m/%d"
site_dir    : _site
paginate    : 5

# User defined variables should be defined here.
site        :
    name        : "Pythoned!"  
    address     : "http://foobarnbaz.com"
    author_name : "Sreejith Kesavan"
    author_email: "sreejithemk@gmail.com"
                
